
// cifar10_cmsisnnet
// This file was @generated by ai8xize.py --test-dir synthed_net --prefix cifar10_cmsisnnet --checkpoint-file trained/training_cmsisnnet_qat_correct_q_1101.tar --sample-input tests/sample_cifar10.npy --config-file networks/cmsisnnet-cifar10.yaml --softmax --device MAX78000 --compact-data --mexpress --timer 0 --display-checkpoint --verbose --overwrite

// Main includes
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include "mxc.h"
#include "cnn.h"

// Camera
#include "mxc_device.h"
#include "board.h"
#include "mxc_delay.h"
#include "camera.h"
#include "dma.h"
#define IMAGE_XRES  32											// X-resolution
#define IMAGE_YRES  32											// Y-resolution
#define CAMERA_FREQ 10000000								// Frequency (10M)

// Our files
#include "label_names10.h"

// Samples
#include "sampledata1.h"
#include "sampledata2.h"
#include "sampledata3.h"
#include "sampledata4.h"
#include "sampledata5.h"
#include "sampledata6.h"
#include "sampledata7.h"
#include "sampledata8.h"
#include "sampledata9.h"
#include "sampleoutput.h" 


volatile uint32_t cnn_time; // Stopwatch


// 3-channel 32x32 data input (3072 bytes total / 1024 bytes per channel):
// HWC 32x32, channels 0 to 2

// Sample inputs
static uint32_t input_1[] = SAMPLE_INPUT_1;
static uint32_t input_2[] = SAMPLE_INPUT_2;
static uint32_t input_3[] = SAMPLE_INPUT_3;
static uint32_t input_4[] = SAMPLE_INPUT_4;
static uint32_t input_5[] = SAMPLE_INPUT_5;
static uint32_t input_6[] = SAMPLE_INPUT_6;
static uint32_t input_7[] = SAMPLE_INPUT_7;
static uint32_t input_8[] = SAMPLE_INPUT_8;
static uint32_t input_9[] = SAMPLE_INPUT_9;

uint32_t input_img[1024] ;

void load_input(uint8_t* RawData, int print_photo, int demo_mode)
{
  int i;
  //const uint32_t *in0 = input_0;
  uint8_t* data_ptr = RawData;
  uint8_t ur, ug, ub, uzero;      // Colors
  for (i = 0; i < 1024; i++)     // for each pixel // RGB 888
  {
    ur = data_ptr[ i*4+0 ]; 
    ug = data_ptr[ i*4+1 ];
    ub = data_ptr[ i*4+2 ];
    uzero = data_ptr[ i*4+3 ];
    ur += 128; ug += 128;  ub += 128;
    input_img[i] = 0xFFFFFFFF & ((uzero << 24) | (ur << 16) | (ug << 8) | ub) ;
    //printf("0x%-8x|", 0xFFFFFFFF & ((uzero << 24) | (ur << 16) | (ug << 8) | ub));
    //while (((*((volatile uint32_t *) 0x50000004) & 1)) != 0); // Wait for FIFO 0
    //*((volatile uint32_t *) 0x50000008) = *in0++; // Write FIFO 0
    //*((volatile uint32_t *) 0x50000008) = 0x00FFFFFF & ((ur << 16) | (ug << 8) | ub);
  }
  if (demo_mode == 1) memcpy32((uint32_t *) 0x50400000, input_1, 1024);    // copy example image
  if (demo_mode == 2) memcpy32((uint32_t *) 0x50400000, input_2, 1024);    // copy example image
  if (demo_mode == 3) memcpy32((uint32_t *) 0x50400000, input_3, 1024);    // copy example image
  if (demo_mode == 4) memcpy32((uint32_t *) 0x50400000, input_4, 1024);    // copy example image
  if (demo_mode == 5) memcpy32((uint32_t *) 0x50400000, input_5, 1024);    // copy example image
  if (demo_mode == 6) memcpy32((uint32_t *) 0x50400000, input_6, 1024);    // copy example image
  if (demo_mode == 7) memcpy32((uint32_t *) 0x50400000, input_7, 1024);    // copy example image
  if (demo_mode == 8) memcpy32((uint32_t *) 0x50400000, input_8, 1024);    // copy example image
  if (demo_mode == 9) memcpy32((uint32_t *) 0x50400000, input_9, 1024);    // copy example image
  
  if (demo_mode == 0 ) memcpy32((uint32_t *) 0x50400000, input_img, 1024);  // copy REAL image
  if ((print_photo >0 ) || (demo_mode >0))
  {
    printf("/*\n");
    for (i = 0; i< 1024; i++ )
    {
      if (demo_mode == 0) printf("0x%.8x, ", input_img[i]);
      if (demo_mode == 1) printf("0x%.8x, ", input_1[i]);
      if (demo_mode == 2) printf("0x%.8x, ", input_2[i]);
      if (demo_mode == 3) printf("0x%.8x, ", input_3[i]);
      if (demo_mode == 4) printf("0x%.8x, ", input_4[i]);
      if (demo_mode == 5) printf("0x%.8x, ", input_5[i]);
      if (demo_mode == 6) printf("0x%.8x, ", input_6[i]);
      if (demo_mode == 7) printf("0x%.8x, ", input_7[i]);
      if (demo_mode == 8) printf("0x%.8x, ", input_8[i]);
      if (demo_mode == 9) printf("0x%.8x, ", input_9[i]);
      //printf("0x%.2x%.2x%.2x%.2x, ",uzero,ur,ug,ub);
      if ((i+1) % 32 == 0) printf("\\\n");
    }
    printf("*/\n");
  }
}

// Expected output of layer 7 for cifar10_cmsisnnet 

// Classification layer:
static int32_t ml_data[CNN_NUM_OUTPUTS];
static q15_t ml_softmax[CNN_NUM_OUTPUTS];

void softmax_layer(void)
{
  cnn_unload((uint32_t *) ml_data);
  softmax_q17p14_q15((const q31_t *) ml_data, CNN_NUM_OUTPUTS, ml_softmax);
}

int main(void)
{
  int i;
  int digs, tens;

  MXC_ICC_Enable(MXC_ICC0); // Enable cache

  // Switch to 100 MHz clock
  MXC_SYS_Clock_Select(MXC_SYS_CLOCK_IPO);
  SystemCoreClockUpdate();

  printf("\n **** Welcome to our demo! **** \n");
  printf(" **** Authors: Victor Sainz, Carolina Lopez ****\n");
  printf("\n ** Max78000 FeatherBoard is starting up **\n");

  // DO NOT DELETE THIS LINE:
  MXC_Delay(MSEC(500)); // Let debugger interrupt if needed

  // camera
  int dma_channel;
  uint8_t*  RawData;
  uint32_t  ImageLength, ImageWidth, ImageHeight;
    
  MXC_DMA_Init();												// Initialize the DMA
  dma_channel = MXC_DMA_AcquireChannel();						// DMA channel

  camera_init(CAMERA_FREQ);							// Initialize the camera

  //
  // Setup the camera properties: camera resolution,pixel format,FIFO byte mode,DMA channel
  //
  camera_setup( IMAGE_XRES,         // width
                IMAGE_YRES,         // heigth
                PIXFORMAT_RGB888,   // pixel format
                FIFO_THREE_BYTE,     // FIFO mode
                USE_DMA,            // Set streaming mode
                dma_channel         // Allocate the DMA channel retrieved in initialization
                );
  
  
  printf("********** Camera is ready **********\r\n");
  int print_photo = 1;
  int demo_mode = 5;
  LED_On(LED1);
  printf(" * Demonstration mode is activated, press PB2 to cancel * \n");
  while(1)
  {    // Main loop
    printf("********** Press PB1(SW1) to capture an image **********\r\n");
    while (!PB_Get(0)){
      if (PB_Get(1)){
        if (demo_mode >= 0)
        {
          demo_mode = 0;
          printf(" * Demonstration mode was deactivated * \n");
          LED_Off(LED1);
        }
        if (print_photo >= 1)
        {
          print_photo = 0;
          printf("\n********** NOT TRANSMIT image **********\n");
        }
        else
        {
          print_photo = 1;
          printf("\n********** TRANSMIT image **********\n");
        }
        MXC_Delay(MSEC(500));
      }
    }
  
    LED_Toggle(LED2);   
    camera_start_capture_image();								// Capture image
    //
    // Capture an image and display its properties
    //
    while(1)      // wait until picture is taken
    {
      if (camera_is_image_rcv()) 								// If image received...
      {
        camera_get_image(&RawData, &ImageLength, &ImageWidth, &ImageHeight);
        printf("Camera:\nraw=0x%x imglen=%d w=%d h=%d\n", RawData, ImageLength, ImageWidth, ImageHeight);
        MXC_Delay(MSEC(40));
        break;
      }
    }
    LED_Toggle(LED2);
    printf("Picture taken\n");


    // Enable peripheral, enable CNN interrupt, turn on CNN clock
    // CNN clock: APB (50 MHz) div 1
    cnn_enable(MXC_S_GCR_PCLKDIV_CNNCLKSEL_PCLK, MXC_S_GCR_PCLKDIV_CNNCLKDIV_DIV1);

    printf("\n*** CNN Inference with cifar10 ***\n");

    cnn_init(); // Bring state machine into consistent state
    cnn_load_weights(); // Load kernels
    cnn_load_bias();
    cnn_configure(); // Configure state machine
    
    load_input(RawData, print_photo, demo_mode); // Load data input via FIFO
    if (demo_mode > 0)
    {
      demo_mode++;
      if (demo_mode>9) demo_mode = 1;
    }
    cnn_start(); // Start CNN processing

    while (cnn_time == 0)
    {
      MXC_LP_EnterSleepMode(); // Wait for CNN
    }

    softmax_layer();

    #ifdef CNN_INFERENCE_TIMER
    printf("Approximate data loading and inference time: %u us\n\n", cnn_time);
    #endif

    cnn_disable(); // Shut down CNN clock, disable peripheral

    int max_digs = 0, max_i = 0;

    printf("Classification results:\n");
    for (i = 0; i < CNN_NUM_OUTPUTS; i++) {
      digs = (1000 * ml_softmax[i] + 0x4000) >> 15;
      tens = digs % 10;
      digs = digs / 10;
      //printf("[%7d] -> Class [%s]: %d.%d%%\n", ml_data[i], LABELS[i], digs, tens);
      printf("Class [%-13s]: %2d.%d%%\n", LABELS[i], digs, tens);
      if (digs >= max_digs)
      {
        max_digs = digs;
        max_i = i;
      }
    }
    if (demo_mode)
    {
      printf("|Demo %d|\n",demo_mode);
    }
    printf("\n Predicted class is %s, %2d%%\n\n", LABELS[max_i], max_digs);
  }
  return 0;
}


/*
  SUMMARY OF OPS
  Hardware: 18,724,864 ops (18,589,696 macc; 135,168 comp; 0 add; 0 mul; 0 bitwise)
    Layer 0: 917,504 ops (884,736 macc; 32,768 comp; 0 add; 0 mul; 0 bitwise)
    Layer 1: 9,469,952 ops (9,437,184 macc; 32,768 comp; 0 add; 0 mul; 0 bitwise)
    Layer 2: 2,400,256 ops (2,359,296 macc; 40,960 comp; 0 add; 0 mul; 0 bitwise)
    Layer 3: 2,367,488 ops (2,359,296 macc; 8,192 comp; 0 add; 0 mul; 0 bitwise)
    Layer 4: 1,191,936 ops (1,179,648 macc; 12,288 comp; 0 add; 0 mul; 0 bitwise)
    Layer 5: 2,363,392 ops (2,359,296 macc; 4,096 comp; 0 add; 0 mul; 0 bitwise)
    Layer 6: 4,096 ops (0 macc; 4,096 comp; 0 add; 0 mul; 0 bitwise)
    Layer 7: 10,240 ops (10,240 macc; 0 comp; 0 add; 0 mul; 0 bitwise)

  RESOURCE USAGE
  Weight memory: 94,048 bytes out of 442,368 bytes total (21.3%)
  Bias memory:   266 bytes out of 2,048 bytes total (13.0%)
*/

